# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='zmp',
  serialized_pb='\n\rservice.proto\x12\x03zmp\"6\n\x12ServiceRequestImpl\x12\x0f\n\x07service\x18\x01 \x01(\t\x12\x0f\n\x07request\x18\x02 \x01(\x0c\"\x86\x01\n\x13ServiceResponseImpl\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x1d.zmp.ServiceResponseImpl.Type\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x10\n\x08response\x18\x03 \x01(\x0c\"\x1f\n\x04Type\x12\x0c\n\x08RESPONSE\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x32K\n\x0bServiceImpl\x12<\n\x07Service\x12\x17.zmp.ServiceRequestImpl\x1a\x18.zmp.ServiceResponseImpl')



_SERVICERESPONSEIMPL_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='zmp.ServiceResponseImpl.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESPONSE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=182,
  serialized_end=213,
)


_SERVICEREQUESTIMPL = _descriptor.Descriptor(
  name='ServiceRequestImpl',
  full_name='zmp.ServiceRequestImpl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service', full_name='zmp.ServiceRequestImpl.service', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='request', full_name='zmp.ServiceRequestImpl.request', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=76,
)


_SERVICERESPONSEIMPL = _descriptor.Descriptor(
  name='ServiceResponseImpl',
  full_name='zmp.ServiceResponseImpl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='zmp.ServiceResponseImpl.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service', full_name='zmp.ServiceResponseImpl.service', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='zmp.ServiceResponseImpl.response', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVICERESPONSEIMPL_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=79,
  serialized_end=213,
)

_SERVICERESPONSEIMPL.fields_by_name['type'].enum_type = _SERVICERESPONSEIMPL_TYPE
_SERVICERESPONSEIMPL_TYPE.containing_type = _SERVICERESPONSEIMPL;
DESCRIPTOR.message_types_by_name['ServiceRequestImpl'] = _SERVICEREQUESTIMPL
DESCRIPTOR.message_types_by_name['ServiceResponseImpl'] = _SERVICERESPONSEIMPL

class ServiceRequestImpl(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVICEREQUESTIMPL

  # @@protoc_insertion_point(class_scope:zmp.ServiceRequestImpl)

class ServiceResponseImpl(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SERVICERESPONSEIMPL

  # @@protoc_insertion_point(class_scope:zmp.ServiceResponseImpl)


# @@protoc_insertion_point(module_scope)
